apiVersion: apps/v1
kind: Deployment
metadata:
  name: pedroribeiro-playlist-recommender-deployment
  labels:
    app: pedroribeiro-playlist-recommender-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pedroribeiro-playlist-recommender-pod
  template:
    metadata:
      labels:
        app: pedroribeiro-playlist-recommender-pod
    spec:
      containers:
      - name: api-container
        image: pdrgbr/flask-api:0.4
        ports:
        - containerPort: 32210
        volumeMounts:
        - name: project2-pv-pedroribeiro
          mountPath: /home/pedroribeiro/project2-pv
      terminationGracePeriodSeconds: 900
      volumes:
      - name: project2-pv-pedroribeiro
        persistentVolumeClaim:
          claimName: project2-pvc-pedroribeiro
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
