apiVersion: v1
kind: Service
metadata:
  name: pedroribeiro-playlist-recommender-service
spec:
  selector:
    app: pedroribeiro-playlist-recommender-pod
  ports:
    - protocol: "TCP"
      port: 32210
      targetPort: 32210
  type: LoadBalancer